services:
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server-musa
    command: >
      -hf Qwen/Qwen3-8B-GGUF
      --host 0.0.0.0
      --port 9100
      --threads 4
      --ctx-size 4096
      --batch-size 256
      --jinja
      -fa
    ports:
      - "9100:9100"
    tty: true
