from openai import OpenAI
import json
from datetime import datetime
import pytz
import cv2
import os
import tempfile



import os

# Set API key and base URL
server_url = os.getenv("API_SERVER")

# Initialize the OpenAI client for llama.cpp's server
#client = OpenAI(base_url="http://localhost:9100/v1", api_key="EMPTY")

client = OpenAI(base_url=server_url, api_key="EMPTY")

# Define the tools (functions) for getting the current time and capturing webcam image
tools = [
    {
        "type": "function",
        "function": {
            "name": "get_current_time",
            "description": "Get the current local time for a specified timezone",
            "parameters": {
                "type": "object",
                "properties": {
                    "timezone": {
                        "type": "string",
                        "description": "The IANA timezone name (e.g., Europe/Berlin)"
                    }
                },
                "required": ["timezone"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "capture_webcam_image",
            "description": "Capture a single frame from the default webcam and return a description",
            "parameters": {
                "type": "object",
                "properties": {},
                "required": []
            }
        }
    }
]

# Function to get the current time for a given timezone using pytz
def get_current_time(timezone):
    try:
        tz = pytz.timezone(timezone)
        current_time = datetime.now(tz)
        formatted_time = current_time.strftime("%I:%M:%S %p %Z, %A, %B %d, %Y")
        return {"timezone": timezone, "current_time": formatted_time}
    except pytz.exceptions.UnknownTimeZoneError:
        return {"error": f"Invalid timezone: {timezone}"}
    except Exception as e:
        return {"error": f"Failed to fetch time for {timezone}: {str(e)}"}

# Function to capture a frame from the webcam
def capture_webcam_image():
    try:
        # Initialize the webcam (default device, usually 0)
        cap = cv2.VideoCapture(0)
        if not cap.isOpened():
            return {"error": "Failed to open webcam"}

        # Capture a single frame
        ret, frame = cap.read()
        if not ret:
            cap.release()
            return {"error": "Failed to capture image from webcam"}

        # Create a temporary file to save the image
        with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as temp_file:
            temp_path = temp_file.name
            cv2.imwrite(temp_path, frame)

        # Release the webcam
        cap.release()

        # Placeholder: Assume the model can describe the image
        # In practice, you'd pass the image to an image-capable model
        image_description = {
            "image_path": temp_path,
            "description": "Captured image from webcam (description would be generated by an image-capable model)"
        }

        # Optionally, clean up the temporary file
        try:
            #print("remove")
            os.remove(temp_path)
        except Exception as e:
            print(f"Warning: Could not delete temporary file {temp_path}: {str(e)}")

        return image_description
    except Exception as e:
        return {"error": f"Error capturing webcam image: {str(e)}"}

# Main function to handle the chat interaction
def chat_with_qwen3():
    messages = [
        {"role": "user", "content": "What do you see?"}
    ]

    try:
        response = client.chat.completions.create(
            model="Qwen3-32B",
            messages=messages,
            tools=tools,
            tool_choice="auto",
            temperature=0.6,
            max_tokens=32768
        )

        response_message = response.choices[0].message

        if response_message.tool_calls:
            for tool_call in response_message.tool_calls:
                if tool_call.function.name == "get_current_time":
                    args = json.loads(tool_call.function.arguments)
                    timezone = args.get("timezone", "Europe/Berlin")
                    time_data = get_current_time(timezone)
                    messages.append({
                        "role": "tool",
                        "content": json.dumps(time_data),
                        "tool_call_id": tool_call.id
                    })
                    final_response = client.chat.completions.create(
                        model="Qwen3-32B",
                        messages=messages,
                        temperature=0.6,
                        max_tokens=32768
                    )
                    print(final_response.choices[0].message.content)
                elif tool_call.function.name == "capture_webcam_image":
                    image_data = capture_webcam_image()
                    messages.append({
                        "role": "tool",
                        "content": json.dumps(image_data),
                        "tool_call_id": tool_call.id
                    })
                    final_response = client.chat.completions.create(
                        model="Qwen3-32B",
                        messages=messages,
                        temperature=0.6,
                        max_tokens=32768
                    )
                    print(final_response.choices[0].message.content)
                else:
                    print(f"Unknown tool called: {tool_call.function.name}")
        else:
            print(response_message.content)

    except Exception as e:
        print(f"Error occurred: {str(e)}")

# Run the chat
if __name__ == "__main__":
    chat_with_qwen3()